#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 13 16:49:17 2023

@author: Dean Thomas
"""

import os.path
from deltaB import loop_heatmapworld_ms, plot_heatmapworld_ms, \
    loop_heatmapworld_iono, plot_heatmapworld_iono, \
    loop_heatmapworld_gap, plot_heatmapworld_gap, \
    plot_heatmapworld_ms_total, \
    loop_heatmapworld_ms_by_region, plot_heatmapworld_ms_by_region, \
    plot_heatmapworld_ms_by_region_grid, plot_heatmapworld_ms_by_currents_grid, \
    plot_heatmapworld_ms_by_currents_grid2, \
    plot_histogram_ms_by_region_grid, plot_histogram_ms_by_currents_grid, \
    date_timeISO, create_directory

from Chigomezyo_Ngwira_092112_3a_info import info as info 
from Chigomezyo_Ngwira_092112_3a_info import setup as setup

############################################################################
#
# Script to generate heatmaps for paper
#
############################################################################

if __name__ == "__main__":
    
    # Max/min of scale used in heatmaps
    VMIN = -2500
    VMAX = +2500

    # We will plot the magnitude of the B field in a lat/long grid
    # Define the grid size
    NLAT = 30
    NLONG = 60
    
    BINWIDTH = 50
    
    DELTAHR = 5.5

    # The times for the files that we will process
    TIMES = ((2003, 9, 2, 0, 0, 0),
              (2003, 9, 2, 1, 0, 0),
              (2003, 9, 2, 2, 0, 0),
              (2003, 9, 2, 3, 0, 0),
              (2003, 9, 2, 4, 0, 0))
 
    # Magnetopause and bow shock offsets along x-axis (GSM).  In this case,
    # used to include current layer on surface of bow shock
    DELTAMP = 0.
    DELTABS = 0.5
    
    # Neutral sheet thickness
    THICKNESSNS = 6.
    
    # Radius of near earth region
    NEARRADIUS = 6.6
    
    ###################
    # magnetopause, bow shock and neutral sheet. Files contain their locations
    # NOTE: files are generated by Chigomezyo_Ngwira_092112_3a_FindBoundaries.py
    ###################

    mpfiles = ('3d__var_1_e20030902-000000-000.out.cdf.30.0-91.magnetopause.pkl',
                '3d__var_1_e20030902-010000-000.out.cdf.30.0-91.magnetopause.pkl',
                '3d__var_1_e20030902-020000-000.out.cdf.30.0-91.magnetopause.pkl',
                '3d__var_1_e20030902-030000-000.out.cdf.30.0-91.magnetopause.pkl',
                '3d__var_1_e20030902-040000-000.out.cdf.30.0-91.magnetopause.pkl')
 
    bsfiles = ('3d__var_1_e20030902-000000-000.out.cdf.64-65.bowshock.pkl',
                '3d__var_1_e20030902-010000-000.out.cdf.64-65.bowshock.pkl',
                '3d__var_1_e20030902-020000-000.out.cdf.64-65.bowshock.pkl',
                '3d__var_1_e20030902-030000-000.out.cdf.64-65.bowshock.pkl',
                '3d__var_1_e20030902-040000-000.out.cdf.64-65.bowshock.pkl')
 
    nsfiles = ('3d__var_1_e20030902-000000-000.out.cdf.200.0-201.neutralsheet.pkl',
                '3d__var_1_e20030902-010000-000.out.cdf.200.0-201.neutralsheet.pkl',
                '3d__var_1_e20030902-020000-000.out.cdf.200.0-201.neutralsheet.pkl',
                '3d__var_1_e20030902-030000-000.out.cdf.200.0-201.neutralsheet.pkl',
                '3d__var_1_e20030902-040000-000.out.cdf.200.0-201.neutralsheet.pkl')
     
    # Get a list of BATSRUS and RIM files. info parameters define location 
    # (dir_run) and file types.  Based on info structure from magnetopost.
    # NOTE: magnetopost code fails on this, so a modified version of setup
    # is in Chigomezyo_Ngwira_092112_3a_info
    setup(info)
    
    # Calculate the delta B sums to get Bn contributions from 
    # various current systems in the magnetosphere, gap region, and 
    # the ionosphere over a lat-long grid
    loop_heatmapworld_ms( info, TIMES, NLAT, NLONG, deltahr=DELTAHR )
    loop_heatmapworld_iono( info, TIMES, NLAT, NLONG, deltahr=DELTAHR )
    loop_heatmapworld_gap( info, TIMES, NLAT, NLONG, nR=100, deltahr=DELTAHR, \
                          useRIM=True)
    loop_heatmapworld_ms_by_region( info, TIMES, NLAT, NLONG, DELTAMP, DELTABS, 
                            THICKNESSNS, NEARRADIUS, mpfiles, bsfiles, nsfiles, 
                            deltahr=DELTAHR )

    # Create heatmaps plots of Bn over earth
    # plot_heatmapworld_ms( info, TIMES, VMIN, VMAX, NLAT, NLONG )
    # plot_heatmapworld_ms_total( info, TIMES, VMIN, VMAX, NLAT, NLONG, csys='GEO', threesixty=False )
    # plot_heatmapworld_iono( info, TIMES, VMIN, VMAX, NLAT, NLONG, csys='SM', threesixty=True )
    # plot_heatmapworld_gap( info, TIMES, VMIN, VMAX, NLAT, NLONG, csys='GEO', threesixty=False )
    # plot_heatmapworld_ms_by_region( info, TIMES, VMIN, VMAX, NLAT, NLONG, DELTAMP, DELTABS, 
    #                         THICKNESSNS, NEARRADIUS)

    plot_heatmapworld_ms_by_region_grid(info, TIMES, VMIN, VMAX, NLAT, NLONG, 
                                        DELTAMP, DELTABS, THICKNESSNS, NEARRADIUS, 
                                        threesixty=False, axisticks=False,
                                        deltahr=DELTAHR)
    plot_heatmapworld_ms_by_currents_grid(info, TIMES, VMIN, VMAX, NLAT, NLONG, 
                                          threesixty=False, axisticks=False,
                                          deltahr=DELTAHR) 
    plot_heatmapworld_ms_by_currents_grid2(info, TIMES, VMIN, VMAX, NLAT, NLONG, 
                                          threesixty=False, axisticks=False,
                                          deltahr=DELTAHR) 

    # plot_histogram_ms_by_region_grid(info, TIMES, VMIN, VMAX, BINWIDTH, 
    #                                   DELTAMP, DELTABS, THICKNESSNS, NEARRADIUS)
    # plot_histogram_ms_by_currents_grid(info, TIMES, VMIN, VMAX, BINWIDTH) 
    # plot_histogram_ms_by_region_grid(info, TIMES, None, None, BINWIDTH, 
    #                                   DELTAMP, DELTABS, THICKNESSNS, NEARRADIUS, 
    #                                   sharex=False, sharey=False, deltahr=DELTAHR)
    # plot_histogram_ms_by_currents_grid(info, TIMES, None, None, BINWIDTH, 
    #                                     sharex=False, sharey=False, deltahr=DELTAHR) 
    

